services:
  api:
    container_name: demo-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://demo-db:3306/demoproj
      MYSQL_ROOT_PASSWORD: Por_160902
    depends_on:
      - demo-db

  demo-db:
    container_name: demo-db
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Por_160902
      MYSQL_DATABASE: demoproj

    volumes:
      - ./data:/var/lib/mysql
